### ISSUE TITLE
[Bug] Error: Invalid URL format

### ISSUE THREAD

**Issue by T-prog3** [Jettcodey/TikTok-Downloader#17]
**Describe the bug**
There seem to be an issue with older videos that have a VideoID lower than around 6500000000000000000. Anything lower results in "Error: Invalid URL format - " and a random video being saved as "_Save.mp4".

Here is an example: https://www.tiktok.com/@brunomars/video/216830520645611520

**To Reproduce**
1. Just download anything older than ~6500000000000000000

**Comment by Jettcodey** [comment]
Crap, random videos are being downloaded again when an error occurs?! I thought I had fixed that issue already.
I'll take a look at these two issues as soon as possible.

**Comment by Jettcodey** [comment]
Hey @T-prog3 ,
The URL length for the validation check was set too high. I've fixed that issue, but the given example URL won’t work using the `SD` download options. I’m closing this issue now because the problem with the example URL is most likely the same as in [Issue #14](https://github.com/Jettcodey/TikTok-Downloader/issues/14).
