### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by xathian** [Jettcodey/TikTok-Downloader#4]
Installed. Selected "Mass download by user name". Hit down and it opens a browser to log in. I log in and nothing happens, it just sits there on the page.

**Comment by Jettcodey** [comment]
Apologies for the inconvenience caused. I realize that I should have been clearer in the readme file regarding the requirement of logging in; instead, you can continue as a guest. This approach is essential for two reasons:

1. TikTok may flag your account due to the unnatural behavior associated with auto-scrolling/loading of a user page. If you were to log in for each content download, TikTok might interpret this as bot-like behavior, potentially leading to **account suspension**. 

> **The downloader employs a temporary browser profile, meaning all associated data, including saved login sessions, is wiped after each download.**

2. The code is designed to operate without the need for login credentials. Any attempt to log in will trigger an exception in the background, causing the code execution to halt abruptly.

Regarding user interaction, the only action required is solving a simple puzzle slide at the beginning to "verify" that you are human, and accepting/denying cookies, which will be deleted anyway.

Additionally, I assume you are using one of the supported browsers. If not, please let me know so that I can provide further assistance.
