### ISSUE TITLE
TikTokDownloaderLog

### ISSUE THREAD

**Issue by V3DX** [Jettcodey/TikTok-Downloader#7]
Is there an option to save the TikTokDownloaderLog text files to a separate folder other than desktop?

**Comment by Jettcodey** [comment]
Hey Mate,
Currently, there is no way to save them in another place, and it's intentional that the logs are put on the Desktop. This way, if you encounter any issues while downloading, you can upload the log directly here. If everything worked great, you can delete it instantly.

However, I am currently working on a new option in the settings menu to disable them entirely.

**Comment by Jettcodey** [comment]
Logs can now be Disabled in the Settings Menu
